// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeOZHZHRGBDFmWIVXl6wheJm2d5S913Us',
    appId: '1:690760879058:web:dbb4206929b7eeeada160b',
    messagingSenderId: '690760879058',
    projectId: 'chat-app-10b81',
    authDomain: 'chat-app-10b81.firebaseapp.com',
    storageBucket: 'chat-app-10b81.firebasestorage.app',
    measurementId: 'G-KHJNXXPM2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavYpilipnQolve80luqcAcx-1BMBsTV0',
    appId: '1:690760879058:android:e688b0a038583a28da160b',
    messagingSenderId: '690760879058',
    projectId: 'chat-app-10b81',
    storageBucket: 'chat-app-10b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdEs7jSc86G_zcAaugP24zf5mRrkNZZA',
    appId: '1:690760879058:ios:f0ceff2da706054bda160b',
    messagingSenderId: '690760879058',
    projectId: 'chat-app-10b81',
    storageBucket: 'chat-app-10b81.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdEs7jSc86G_zcAaugP24zf5mRrkNZZA',
    appId: '1:690760879058:ios:f0ceff2da706054bda160b',
    messagingSenderId: '690760879058',
    projectId: 'chat-app-10b81',
    storageBucket: 'chat-app-10b81.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeOZHZHRGBDFmWIVXl6wheJm2d5S913Us',
    appId: '1:690760879058:web:a46d901dd43e6558da160b',
    messagingSenderId: '690760879058',
    projectId: 'chat-app-10b81',
    authDomain: 'chat-app-10b81.firebaseapp.com',
    storageBucket: 'chat-app-10b81.firebasestorage.app',
    measurementId: 'G-WN9FNPB4W5',
  );
}
